### ISSUE TITLE
Migrate Makefile to Invoke

### ISSUE THREAD

**Issue by alfoltran** [darkroomdevs/github-metrics-backend#4]
### Description

We will use Invoke for the build and CI tasks instead of the Makefile.

### Tasks

- [ ] Migrate settings and scripts
- [ ] Remove Makefile and its dependencies
- [ ] Integrate with TravisCI
