### ISSUE TITLE
Configure Test Coverage

### ISSUE THREAD

**Issue by alfoltran** [darkroomdevs/github-metrics-backend#9]
### Description

Configure a test covarage and publish the results on **Code Climate**.

The Code Climate test coverage reporter takes a supported test coverage report, transforms it into a generalized format, and submits it to Code Climate.

### Tasks

A few important notes when setting up test coverage reporting with Code Climate:

- [ ] You must instrument test coverage yourself as part of your CI build (in one of our supported languages and formats).
- [ ] The test reporter is distributed as a pre-built binary (cc-test-reporter). It gathers the output of your test suite, transforms the output into a generalized format, then uploads the resulting file to a Code Climate API endpoint.
- [ ] The test reporter uses a variety of subcommands. The simplest use case requires only 2 subcommands (cc-test-reporter before-build, cc-test-reporter after-build). More complex use cases (such as parallel builds or multiple test suites) require additional subcommands (cc-test-reporter format-coverage, cc-test-reporter sum-coverage, cc-test-reporter upload-coverage).
- [ ] We require two ENV vars (GIT_COMMIT_SHA and GIT_BRANCH) to be included in your test reports. These are included by default on most CI tools.

### Reference

https://docs.codeclimate.com/docs/configuring-test-coverage
